export const ConfigService = {
    REACT_APP_AUTH0_DOMAIN: process.env.REACT_APP_AUTH0_DOMAIN,
    REACT_APP_AUTH0_CLIENT_ID: process.env.REACT_APP_AUTH0_CLIENT_ID,
    REACT_APP_AUTH0_AUDIENCE: process.env.REACT_APP_AUTH0_AUDIENCE,
    REACT_APP_API_URL: process.env.REACT_APP_API_URL,
    REACT_APP_HASURA_ADMIN_SECRET: process.env.REACT_APP_HASURA_ADMIN_SECRET,
}
